config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  get "/listings/search" => "listings#search", as: "listings_search"

root 'users#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, except: :index do
    resources :reservations, only: [:new]
  end

  resources :reservations, only: [:create, :destroy]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id/show" => "users#show", as: "user_show"
  get "/users/:id/edit" => "users#edit", as: "user_edit"
  patch "/users/:id/update" => "users#update", as: "user_update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  post 'braintree/checkout'

  # resources :reservations do
  #   member do
  #     get 'braintree/new'
  #     post 'braintree/create'
  #   end
  # end
  
  get "/listings/:listing_id/reservations/:id" => "braintree#new", as: "braintree_new_reservation_listing"
  post "/listings/:listing_id/reservations/:id" => "braintree#checkout", as: "braintree_checkout_reservation_listing"

  

end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :reservations

	mount_uploaders :photos, PhotoUploader
  	serialize :avatars, Array

  	def self.search (params)
		results = Listing.all

		results = results.where("name LIKE ?", "%#{params[:keyword]}%") if params[:keyword].present?
		results = results.where("property_type LIKE ?", params[:category]) if params[:category].present?
		results = results.where("guest_number >= ?", params[:number_guest]) if params[:number_guest].present? 
		results = results.where("price >= ?", params[:min_price]) if params[:min_price].present?
		results = results.where("price <= ?", params[:max_price]) if params[:max_price].present?

		return results
	end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :show_listing_params, only: [:show, :edit, :update, :destroy]

	def show
		@user=User.find(@listing.user_id)
		@reservation = Reservation.where(user_id: current_user.id)
		render 'listings/show'
	end

	def new
		render '/listings/new'
	end

	def create
		@user = User.find(current_user.id)
		@newlisting = Listing.new(listing_params)
		@newlisting.save
		@listing = Listing.where(id: current_user.id)
		redirect_to user_show_path(@user.id)
	end

	def edit
		render 'listings/edit'
	end

	def update
		@user = User.find(current_user.id)
		@listing.update(listing_params)
		show_listing_params
		redirect_to listing_path(@user.id)
	end

	def destroy
		@user = User.find(current_user.id)
		@listing.destroy
		redirect_to user_show_path(@user.id)
	end

	

	private

	def show_listing_params
		@listing = Listing.find(params[:id])
	end

	def listing_params
		params.require(:listing).permit(:name, :place_type, :property_type, :room_number, 
			:bed_number, :guest_number, :country, :state, :city, :zipcode, :address, :price, :description, :user_id, {photos:[]})
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container formImg">
<%= form_for @listing, url: listing_path(@listing.id), method: :patch do |form| %>
      
	<div class="create_listing_form">
	    <div>
	     	<h3>Name</h3>
	      	<%= form.text_field :name, placeholder: 'Name'%>
	    </div>
	</div>

	<div class="create_listing_form">
	  	<div>
	    	<h3>Place Type</h3>
	   	 	<%= form.text_field :place_type, placeholder: 'Place Type'%>
	 	 </div>
	</div>
	  
	<div class="create_listing_form">
	  	<div>
	    	<h3>Property Type</h3>
	    	<%= form.text_field :property_type, placeholder: 'Property Type'%>
	  	</div>
	</div>
	  
	<div class="create_listing_form">
	    <div>
	      	<h3>Room Number</h3>
	      	<%= form.text_field :room_number, placeholder: 'Room Number'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>Bed Number</h3>
	      	<%= form.text_field :bed_number, placeholder: 'Bed Number'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>Guest Number</h3>
	      	<%= form.text_field :guest_number, placeholder: 'Guest Number'%>
	    </div>
	</div>
	  
	<div class="create_listing_form">
	    <div>
	      	<h3>Country</h3>
	      	<%= form.text_field :country, placeholder: 'Country'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>State</h3>
	      	<%= form.text_field :state, placeholder: 'State'%>
	    </div>
	</div>
	  
	<div class="create_listing_form">
	    <div>
	      	<h3>City</h3>
	      	<%= form.text_field :city, placeholder: 'City'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>Zip Code</h3>
	      	<%= form.text_field :zipcode, placeholder: 'Zip Code'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>Address</h3>
	      	<%= form.text_field :address, placeholder: 'Address'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>Price</h3>
	      	<%= form.text_field :price, placeholder: 'Price'%>
	    </div>
	</div>

	<div class="create_listing_form">
	    <div>
	      	<h3>Description</h3>
	      	<%= form.text_field :description, placeholder: 'Description'%>
	    </div>
	</div>
	</br>

	<div class="create_listing_form">
	    <div>
    	<%= form.file_field :photos, multiple: true%>
    	</div>
    </div>
    </br>

    <div class="create_listing_form">
	    <div>
	    	<%= form.submit "Confirm", class: "btn btn-primary" %>
	    </div>
	</div>
    
<% end %>

</div>

<%= render partial: "/layouts/footer" %>

app/views/listings/new.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container formImg">

<%= form_for :listing, url:listings_path do |form| %>
  
  <div class="create_listing_form">
    <div>
      <h3>Name</h3>
      <%= form.text_field :name, placeholder: 'Name'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Place Type</h3>
      <%= form.text_field :place_type, placeholder: 'Place Type'%>
    </div>
  </div>
  
  <div class="create_listing_form">
    <div>
      <h3>Property Type</h3>
      <%= form.text_field :property_type, placeholder: 'Property Type'%>
    </div>
  </div>
  
  <div class="create_listing_form">
    <div>
      <h3>Room Number</h3>
      <%= form.text_field :room_number, placeholder: 'Room Number'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Bed Number</h3>
      <%= form.text_field :bed_number, placeholder: 'Bed Number'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Guest Number</h3>
      <%= form.text_field :guest_number, placeholder: 'Guest Number'%>
    </div>
  </div>
  
  <div class="create_listing_form">
    <div>
      <h3>Country</h3>
      <%= form.text_field :country, placeholder: 'Country'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>State</h3>
      <%= form.text_field :state, placeholder: 'State'%>
    </div>
  </div>
  
  <div class="create_listing_form">
    <div>
      <h3>City</h3>
      <%= form.text_field :city, placeholder: 'City'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Zip Code</h3>
      <%= form.text_field :zipcode, placeholder: 'Zip Code'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Address</h3>
      <%= form.text_field :address, placeholder: 'Address'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Price</h3>
      <%= form.text_field :price, placeholder: 'Price'%>
    </div>
  </div>

  <div class="create_listing_form">
    <div>
      <h3>Description</h3>
      <%= form.text_field :description, placeholder: 'Description'%>
    </div>
  </div>
  </br>
  <div class="create_listing_form">
    <div>
      <h3>Please upload exactly 3 profile photos</h3>
      <%= form.file_field :photos, multiple: true %>
    </div>
  </div>
  </br>

  <%= form.hidden_field :user_id ,value: current_user.id %>

  <div class="create_listing_form">
    <div>
    <%= form.submit "Confirm", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

</div>

<%= render partial: "/layouts/footer" %>

app/views/listings/search.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container" id="searchContainer">
	<%= form_tag listings_search_path, method: "get" do %>

	<div class="form-group">	
      <%= label_tag("Keyword") %>
      <%= text_field_tag :keyword, params[:keyword],class:"form-control" %>
    </div>

    <div class="form-group">
    <% @categories = Listing.uniq.pluck(:property_type) %>
      <%= label_tag("Category") %>
      <%= select_tag(:category, options_for_select(@categories),include_blank: true,class:"form-control") %>
    </div>

    <div class="form-group">
      <%= label_tag("Number of Guest") %>
      <%= number_field_tag(:number_guest, params[:number_guest],class:"form-control") %>
    </div>

    <div class="form-group">
      <%= label_tag("Min_price") %>
      <%= number_field_tag(:min_price, params[:min_price],class:"form-control") %>
    </div>

    <div class="form-group">
      <%= label_tag("Max_price") %>
      <%= number_field_tag(:max_price, params[:max_price],class:"form-control") %>
    </div>

    <div class="form-group">
      <%= submit_tag("Search", class: "btn btn-large btn-primary") %>
    </div>
    <% end %>
    <%= link_to "Back to Home", root_path, class: "btn btn-large btn-primary" %>
</div>

</br></br>
<div class="container">
<div class="row">
	<table class="table table-hover">
	    <thead>
	      <tr>
	        <th>Property Name</th>
	        <th>Category</th>
	        <th>Num of Guests</th>
	        <th>Price</th>
	      </tr>
	    </thead>
		<% Listing.search(params).each do |t| %>
		<% if Listing.search(params) != Listing.all%>
			<tbody>
				<tr>
				    <td><%= t.name %></td>
				    <td><%= t.property_type %></td>
				    <td><%= t.guest_number %></td>
				    <td><%= t.price %></td>
				</tr>
			</tbody>
		<% else %>
		<% end %>
		<% end %>
				    
  	</table>
</div>
</div>

app/views/listings/show.html.erb
<%= render partial: "/layouts/navbar" %>


<div id="listingImage">
	<% if @listing.photos == []  %>
		<%= image_tag ("emptyprofileimage.jpg") %>	
	<% else %>
		<%= image_tag @listing.photos.first %>
	<% end %>
</div>
</br>

<div id='listing_profile' class='container'>
	<div id='listing_profile_left'>
		<div>
			<h5><a href="#">Overview </a> · <a href="#">Reviews</a> · <a href="#">The Host</a> · <a href="#">Location</a> </h5>
		</div>
		<div id="listing_userprofile">
			<div>
				<h1><%= @listing.name%></h1>
				<h5><%= @listing.property_type%></h5>
				<h5><%= @listing.guest_number%> guests · <%= @listing.room_number%> bedrooms · <%= @listing.bed_number %> beds</h5>
				<h5><%= @listing.description%></h5>
				<% if current_user.id == @user.id %>
					<%= link_to "Edit Listing", edit_listing_path %>
					<%= link_to "Delete Listing", listing_path(@listing.id), method: :delete, data:{confirm: "Are You Confirm to Delete??"} %>
				<% end %>
			</div>
			<div>
				<% if @user.photos == []  %>
					<a href="/users/<%= @listing.user_id %>/show"><%= image_tag ("emptyprofileimage.jpg") %></a>	
				<% else %>
					<a href="/users/<%= @listing.user_id %>/show"><%= image_tag @user.photos.first %></a>
				<% end %>
			</div>
				
		</div>
	</div>

	<div id='listing_profile_right'>
		<div>
			<% if @user.photos == []  %>
				<%= image_tag ("emptyprofileimage.jpg"), class: "listing_profile_right_picture" %>	
			<% else %>
				<%= image_tag @user.photos.first %>
			<% end %>
			<h4>RM <%= @listing.price%> per night</h4>
			<div>
				<%= button_to "Book", "/listings/#{@listing.id}/reservations/new", :method => "get", class: "button" %>
			</div>
		</div>
	</div>
</div>

<%= render partial: "/layouts/footer" %>