config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  get "/listings/search" => "listings#search", as: "listings_search"

root 'users#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, except: :index do
    resources :reservations, only: [:new]
  end

  resources :reservations, only: [:create, :destroy]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id/show" => "users#show", as: "user_show"
  get "/users/:id/edit" => "users#edit", as: "user_edit"
  patch "/users/:id/update" => "users#update", as: "user_update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  post 'braintree/checkout'

  # resources :reservations do
  #   member do
  #     get 'braintree/new'
  #     post 'braintree/create'
  #   end
  # end
  
  get "/listings/:listing_id/reservations/:id" => "braintree#new", as: "braintree_new_reservation_listing"
  post "/listings/:listing_id/reservations/:id" => "braintree#checkout", as: "braintree_checkout_reservation_listing"

  

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  
  mount_uploaders :photos, PhotoUploader
  serialize :avatars, Array

    def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
        #name: auth_hash["name"],
        first_name: auth_hash["extra"]["raw_info"]["first_name"],
        last_name: auth_hash["extra"]["raw_info"]["last_name"],
        email: auth_hash["extra"]["raw_info"]["email"],
        password: SecureRandom.hex(16)
      )
      user.authentications << authentication
      return user
    end

    # grab fb_token to access Facebook for user data
    def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	before_action :find_user, only: [:show, :edit, :update, :destroy] 

	def index
		@listing = Listing.order(updated_at: :desc).page params[:page]
		render 'layouts/homepage'
	end

	def create
		@listing = Listing.order(updated_at: :desc).page params[:page]
		@user = User.new(user_params)
		if @user.save
			SendEmailAsyncJob.perform_later(@user.id)
		else

		end
		render 'layouts/homepage'
	end

	def show
		@booking = @user.reservations
		@listing = Listing.where(user_id: params[:id])
		@reservation = Reservation.where(user_id: params[:id] )
		render 'users/show'
	end

	def edit
		render 'users/edit'
	end

	def update
		@booking = @user.reservations
		@user.update(user_params)
		@reservation = Reservation.where(user_id: params[:id])
		@listing = Listing.where(user_id: params[:id])
		render 'users/show'
	end

	def destroy

	end

	private

	def find_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, {photos:[]} )
	end

end

app/views/users/_new.html.erb
<%= form_for User.new, url: users_path do |form| %>
      
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-font"></span></span>
        <%= form.text_field :first_name, placeholder: 'First Name', class:"form-control"%>
    </div>

    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-font"></span></span>
        <%= form.text_field :last_name, placeholder: 'Last Name', class:"form-control" %>
    </div>

    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-envelope"></span></span>
        <%= form.text_field :email, placeholder: 'Email' , class:"form-control"%>
    </div>


    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-eye-close"></span></span>
        <%= form.password_field :password ,placeholder: 'Password' , class:"form-control"%>
    </div>

    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-eye-close"></span></span>
        <%= form.file_field :photos, multiple: true , class:"form-control"%>
    </div>
    </br>

    <button type="button" onclick="window.location.href='/auth/facebook'" class="btn btn-primary form-control"><i class="fa fa-facebook"></i> &nbsp; Continue with Facebook</button>

    <div class="modal-footer">
      </br>

      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= form.submit "Confirm", class: "btn btn-primary" %>
    </div>
    
<% end %>



   

app/views/users/edit.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container formImg">
<%= form_for @user, url: user_update_path(@user.id) do |form| %>
      
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-font"></span></span>
        <%= form.text_field :first_name, placeholder: 'First Name', class:"form-control"%>
    </div>

    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-font"></span></span>
        <%= form.text_field :last_name, placeholder: 'Last Name', class:"form-control" %>
    </div>

    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-envelope"></span></span>
        <%= form.text_field :email, placeholder: 'Email' , class:"form-control"%>
    </div>


    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-eye-close"></span></span>
        <%= form.password_field :password ,placeholder: 'Password' , class:"form-control"%>
    </div>

    	<%= form.file_field :photos, multiple: true%>
    </br>

    <div class="modal-footer">
      </br>

      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= form.submit "Confirm", class: "btn btn-primary" %>
    </div>
    
<% end %>

</div>

<%= render partial: "/layouts/footer" %>

app/views/users/show.html.erb
<%= render partial: "/layouts/navbar" %>

<div id="user_profile" class="container">
	<div id="user_profile_left">
		<div>
		
		<% if @user.photos == [] %>
			<div>
				<%= image_tag ("emptyprofileimage.jpg") %>		
			</div>
		<% else %>
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <ol class="carousel-indicators">
				    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				    <li data-target="#myCarousel" data-slide-to="1"></li>
				    <li data-target="#myCarousel" data-slide-to="2"></li>
				  </ol>

				  <!-- Wrapper for slides -->
					<div class="carousel-inner">
					  <div class="item active">
					    <%= image_tag @user.photos.first %>
					  </div>

					  <div class="item">
					    <%= image_tag @user.photos.second %>
					  </div>

					  <div class="item">
					    <%= image_tag @user.photos.third %>
					  </div>
					</div>

				  <!-- Left and right controls -->
				  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
		<% end %>

		</div>
		</br>

		<div class="user_profile_left_header">
			<p>Verified Info</p>			
		</div>
		<div class="user_profile_verification_info">
			<div>
				<ul>
					<li>Government ID</li>
					<li>Email Address</li>
					<li>Phone Number</li>
					<li>Work Email</li>
				</ul>
			</div>
			<div>
				<ul>
					<li><i class="fa fa-check" aria-hidden="true"></i></li>
					<li><i class="fa fa-check" aria-hidden="true"></i></li>
					<li><i class="fa fa-check" aria-hidden="true"></i></li>
					<li><i class="fa fa-check" aria-hidden="true"></i></li>
				</ul>
			</div>
		</div>
		</br>

		<div class="user_profile_left_header">
			<p>About Me</p>			
		</div>
		<div class="user_profile_verification_info">
			<div>
				<ul>
					<li><p><span class="user_profile_header">School</span></br>Maryland Institute College of Art</p></li>
					<li><p><span class="user_profile_header">Work</span></br>Artists & Designers (UI/UX, Interior Design, Illustration)</p></li>
					<li><p><span class="user_profile_header">Languages</span></br>English</p></li>
				</ul>
			</div>
		</div>

	</div>
	<div id="user_profile_right">
		<div>
			<h1>Hey, I'm <%= @user.last_name %>!</h1> 
			<% if current_user.id == @user.id %>
				<%= link_to "Edit Profile", user_edit_path(@user.id) %>
			<% end %>
			<h5><%=@user.first_name%>, <%=@user.email%>, · Joined in <%=@user.created_at%></h5>
		</div>
		<div>
			<h2>Listings(<%= @listing.count %>)</h2>
			<% @listing.each do |t| %>
			<div class="row">
			  <div class="col-xs-6 col-md-3">
			    <a href="/listings/<%= t.id %>" target="blank" id="user_profile_listings_thumbnail" class="thumbnail">
			      <%= image_tag("profile_listing.jpg") %>
			    </a>
			  </div>
			</div>
			<p><%= t.name %></p>
			<% end %>
		</div>
		<div>
			<h2>Reservation(<%= @booking.count %>)</h2>
			<div class="row">
				<table class="table table-hover">
				    <thead>
				      <tr>
				        <th>Start Date</th>
				        <th>End Date</th>
				        <th>Num of Guests</th>
				        <th>Action</th>
				        <th>Title</th>
				        <th>Price</th>
				        <th>Status</th>
				      </tr>
				    </thead>
			<% @booking.each do |t| %>
				    <tbody>
				      <tr>
				        <td><%= t.start_date.strftime('%d %b %Y') %></td>
				        <td><%= t.end_date.strftime('%d %b %Y') %></td>
				        <td><%= t.num_guests %></td>
				        <td><%= link_to "Delete", reservation_path(t.id),method: :delete, class:"reservation_delete_button" %></td>
				        <td><%= t.listing.name %></td>
				        <td><%= t.total_price %></td>
				        <% if t.unpaid? %>
				        	<td><%= link_to "Pay", braintree_new_reservation_listing_path(t.listing_id,t.id), 'data-turbolinks' => false %></td>
				        <% else %>
				        	<td>Paid</td>
				        <% end %>
				      </tr>
				      </tbody>
			<% end %>
				    
  				</table>
			</div>
		</div>
	</div>
</div>

<%= render partial: "/layouts/footer" %>

<h5><%=@reservation.count%></h5>