config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  get "/listings/search" => "listings#search", as: "listings_search"

root 'users#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, except: :index do
    resources :reservations, only: [:new]
  end

  resources :reservations, only: [:create, :destroy]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/users/:id/show" => "users#show", as: "user_show"
  get "/users/:id/edit" => "users#edit", as: "user_edit"
  patch "/users/:id/update" => "users#update", as: "user_update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  post 'braintree/checkout'

  # resources :reservations do
  #   member do
  #     get 'braintree/new'
  #     post 'braintree/create'
  #   end
  # end
  
  get "/listings/:listing_id/reservations/:id" => "braintree#new", as: "braintree_new_reservation_listing"
  post "/listings/:listing_id/reservations/:id" => "braintree#checkout", as: "braintree_checkout_reservation_listing"

  

end

app/views/layouts/_footer.html.erb
</br>

<div id="footer">
	<div id="footerdiv">
		<ul class="footerdivlist">
			<li>About us</li>
			<li>Career</li>
			<li>Press</li>
			<li>Policies</li>
			<li>Help</li>
			<li>Diversity and Belonging</li>
		</ul>
	</div>
	<div>
		<ul class="footerdivlist">
			<li>Trust & Safety</li>
			<li>Travel Credit</li>
			<li>Gift Cards</li>
			<li>Pairbnb Citizen</li>
			<li>Business Travel</li>
			<li>Guidebooks</li>
			<li>Pairbnbmag</li>
		</ul>
	</div>
	<div>
		<ul class="footerdivlist">
			<li>About us</li>
			<li>Career</li>
			<li>Press</li>
			<li>Policies</li>
			<li>Help</li>
			<li>Diversity and Belonging</li>
		</ul>
	</div>
</div>

<div class="container">
	<div id="footerSocialLink" >
		<div>
			<h5>Pairbnb. Inc</h5>
		</div>
		<div>
			<h5>Terms Privacy Site Map</h5>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a id="navbar_logo_link" href="/"><%= image_tag("cheahhow-pairbnb_720.png",class:"logo") %></a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <span class="glyphicon glyphicon-search form-control"></span>
          <input type="text" class="form-control" placeholder="Search" >
        </div>
      </form>

      <div class="navbar-form navbar-left">
        <%= button_to "Advance Search", "/listings/search", :method => "get", class: "btn btn-default" %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/listings/new">Become a host</a></li>
        <li><a href="#">Help</a></li>

        <% if signed_in? %>
        <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
          <% if current_user.photos == [] %>
            <li><a id="navbar_logo_link" href="/users/<%=current_user.id%>/show"><%= image_tag("emptyprofileimage.jpg",class:"logo")%></li>
          <% else %>
            <li><a id="navbar_logo_link" href="/users/<%=current_user.id%>/show"><%= image_tag current_user.photos.first ,class:"logo"%></li>
          <% end %>
        <% else %>
        <li><a href="#" data-toggle="modal" data-target="#signUpModal">Sign Up</a></li>
        <li><a href="#" data-toggle="modal" data-target="#logInModal">Log In</a></li>
        <% end %>
        <!-- Modal -->
        <div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-center" id="myModalLabel">Log In</h4>
              </div>
              <div class="modal-body">
                <%= render partial: '/sessions/form' %>
              </div>
              
            </div>
          </div>
        </div>

        <div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-center" id="myModalLabel">Sign Up</h4>
              </div>
              <div class="modal-body">
                <%= render partial: '/users/new' %>
              </div>

            </div>
          </div>
        </div>

          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  	<script src="https://use.fontawesome.com/631a0c68a5.js"></script>
    <%= yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<%= render partial: "/layouts/navbar" %>

<div class='container'>
  <% @listing.each do |t| %>
  <a href="/listings/<%= t.id %>" target="blank">
  <div class="listingstyle">
    <div class="thumbnail">
      <%= image_tag("example.jpg") %>
      <div class="caption">
        <h5><%= t.property_type %> · <%= t.bed_number %> BEDS</h5>
        <h4><%= t.name %></h4>
        <h5>RM <%= t.price %> per night</h5>
      </div>
    </div>
  </div>
  </a>
  <% end %>
  <div id='paginate'>
    <div class='container'><%= paginate @listing ,window: 2%></div>
  </div>
</div>

<%= render partial: "/layouts/footer" %>